# Generated by Django 4.2.30 on 2026-04-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flow_intensity', models.CharField(choices=[('light', 'Легкий'), ('heavy', 'Обильный')], max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Запись о цикле',
                'verbose_name_plural': 'Записи о цикле',
            },
        ),
    ]
